MODEL:
  META_ARCHITECTURE: SSLMetaArch
  DEVICE: cuda
  WEIGHTS: ''
  DTYPE: float32
compute_precision:
  param_dtype: bf16
  reduce_dtype: fp32
  sharding_strategy: SHARD_GRAD_OP
dino:
  loss_weight: 1.0
  global_ignore_diagonal: true
  head_n_prototypes: 65536
  head_bottleneck_dim: 256
  head_norm_last_layer: false
  head_nlayers: 3
  head_hidden_dim: 2048
  koleo_loss_weight: 0.1
  koleo_loss_distributed: false
  koleo_topk: 1
  koleo_distributed_replicas: 0
  koleo_distributed_loss_group_size: null
  koleo_distributed_loss_group_data: true
  force_weight_norm: false
  reweight_dino_local_loss: false
  local_loss_weight_schedule:
    start: 0.5
    peak: 0.5
    end: 0.5
    warmup_epochs: 0
ibot:
  loss_weight: 1.0
  mask_sample_probability: 0.5
  mask_ratio_min_max:
  - 0.1
  - 0.5
  mask_random_circular_shift: false
  force_masking_even_with_zero_weight: false
  separate_head: true
  head_n_prototypes: 65536
  head_bottleneck_dim: 256
  head_norm_last_layer: false
  head_nlayers: 3
  head_hidden_dim: 2048
gram:
  use_loss: false
  compute_stats: false
  loss_weight: 1.0
  ema_teacher: false
  ckpt: null
  it_load_ema_teacher: -1
  rep_update: true
  update_frequency: 50000
  it_first_update: 0
  max_updates: null
  normalized: true
  img_level: false
  remove_neg: false
  remove_only_teacher_neg: false
  tokens_used: all
  global_teacher_resize_method: bicubic
  global_teacher_resize_antialias: false
  loss_weight_schedule: null
train:
  batch_size_per_gpu: 64
  dataset_path: BioImageDataset:root=/data1/peerd/spatial_datalake/reyesj3_pancreas_premalignant/15-07/processed/microscopy/15-07_comet_bgsub_warped.ome.tiff:split=TRAIN:source_size=512
  data_config: null
  output_dir: /data1/peerd/moormana/GitHub/andrewmoorman/fossil/.dev/data_loader/notebooks
  saveckp_freq: 20
  seed: 0
  num_workers: 16
  OFFICIAL_EPOCH_LENGTH: 100
  monitor_gradient_norm: false
  chunk_schedule: []
  use_teacher_head: true
  learn_from_teacher_tokens: false
  centering: sinkhorn_knopp
  checkpointing: false
  checkpointing_full: false
  compile: true
  cudagraphs: false
  sharded_eval_checkpoint: false
  cache_dataset: false
  cell_augmentation: false
  cell_augmentation_type: hpa
student:
  arch: vit_small
  patch_size: 16
  drop_path_rate: 0.3
  layerscale: 1.0e-05
  pretrained_weights: null
  ffn_layer: mlp
  ffn_ratio: 4.0
  resume_from_teacher_chkpt: /data1/peerd/moormana/GitHub/andrewmoorman/fossil/weights/dinov3/dinov3_vits16_pretrain_lvd1689m_dinov3_checkpoint.pth
  qkv_bias: true
  proj_bias: true
  ffn_bias: true
  norm_layer: layernorm
  n_storage_tokens: 0
  mask_k_bias: false
  untie_cls_and_patch_norms: false
  untie_global_and_local_cls_norm: false
  in_chans: 7
  pos_embed_type: rope
  pos_embed_rope_base: 100.0
  pos_embed_rope_min_period: null
  pos_embed_rope_max_period: null
  pos_embed_rope_normalize_coords: separate
  pos_embed_rope_shift_coords: null
  pos_embed_rope_jitter_coords: null
  pos_embed_rope_rescale_coords: null
  pos_embed_rope_dtype: bf16
  fp8_enabled: false
  fp8_filter: blocks
  patch_drop: 0.0
teacher:
  momentum_teacher: 0.992
  final_momentum_teacher: 1
  warmup_teacher_temp: 0.04
  teacher_temp: 0.07
  warmup_teacher_temp_epochs: 30
  in_chans: 7
distillation:
  enabled: false
  full_cfg_path: ''
  checkpoint_path: ''
multidistillation:
  enabled: false
hrft:
  enabled: false
  checkpoint_path: ''
optim:
  epochs: 200
  optimizer: adamw
  weight_decay: 0.04
  weight_decay_end: 0.4
  lr: 0.002
  warmup_epochs: 10
  min_lr: 1.0e-06
  schedule_trunc_extra: 0.0
  clip_grad: 3.0
  freeze_last_layer_epochs: 1
  scaling_rule: sqrt_wrt_1024
  patch_embed_lr_mult: 10.0
  dino_head_wd_multiplier: 1.0
  layerwise_decay: 0.9
  multi_tensor_optim: true
  dump_fsdp_weights_path: ''
  adamw_beta1: 0.9
  adamw_beta2: 0.999
crops:
  global_crops_scale:
  - 0.32
  - 1.0
  local_crops_number: 8
  local_crops_scale:
  - 0.05
  - 0.32
  global_crops_size: 224
  local_crops_size: 96
  global_local_crop_pairs_ratios: 1.0
  gram_teacher_crops_size: null
  localcrops_subset_of_globalcrops: false
  share_color_jitter: false
  horizontal_flips: true
  gram_teacher_no_distortions: false
  rgb_mean:
  - 328
  - 1403
  - 42
  - 848
  - 344
  - 1050
  - 117
  rgb_std:
  - 699
  - 2651
  - 132
  - 1698
  - 484
  - 2015
  - 218
  vertical_flips: true
evaluation:
  eval_period_iterations: 12500
  low_freq_every: 5
  config_files:
    high_freq: benchmark_high_frequency.yaml
    low_freq: benchmark_low_frequency.yaml
checkpointing:
  period: 250
  max_to_keep: 3
  keep_every: 99999999999999999
